#pragma once

// I2C for OLED on BLOK (GP16=SDA, GP17=SCL)
#define I2C_DRIVER I2CD0
#define I2C0_SDA_PIN GP16
#define I2C0_SCL_PIN GP17

// RGB Matrix - 70 LEDs (35 per side)
#define RGB_MATRIX_LED_COUNT 70
#define RGB_MATRIX_SPLIT { 35, 35 }
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150

// Enable reactive effects
#define RGB_MATRIX_KEYPRESSES
#define SPLIT_TRANSPORT_MIRROR

// Default effect
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS

// Enable these animations
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define ENABLE_RGB_MATRIX_BREATHING
